### ISSUE TITLE
Question about plugins

### ISSUE THREAD

**Issue by cl2raul66** [jfversluis/Plugin.Maui.Feature#1]
Hello and congratulations for this great contribution that I was waiting for something like this for a long time, but I need if you could clarify a question about this template... In the .Net Framework there was something called managed extensibility framework (MFE). When switching to .Net Core, this didn't exist... My question is, does your template do the same function as MEF? Thank you very much for your work.

**Comment by jfversluis** [comment]
Thank you!

No, this is just a template that can be used as a starting point for your .NET MAUI plugin development. This is basically just a File > New Project from Visual Studio with some changes with how I like to setup my plugins hoping that it will help others.
